[package]
name = "jlog-cli"  # or "jlogtool", "flog", etc.
version = "0.1.0"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
rusqlite = "0.29"
chrono = "0.4"
dirs = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
